name: Build and Generate Video

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_package:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --progress-bar=off --quiet --upgrade pip
        pip install --progress-bar=off --quiet build

    - name: Build package
      run: make build

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: videonoise_package
        path: dist/*.whl

  generate_video:
    needs: build_package
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install FFmpeg
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq --no-install-recommends -y ffmpeg

    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: videonoise_package
        path: dist

    - name: Install package
      run: pip install --progress-bar=off --find-links file://${{ github.workspace }}/dist videonoise

    - name: Generate short video
      run: videonoise short_video.mp4 -w 640 -t 480 -f 30 -d 5

    - name: Upload short video
      uses: actions/upload-artifact@v2
      with:
        name: short_video
        path: short_video.mp4
